### ISSUE TITLE
Is checking of received remote group elements against the neutral element actually properly implemented?

### ISSUE THREAD

**Issue by BjoernMHaase** [jedisct1/cpace#1]
Hi all,

from reading the code, I did not see whether verification of incoming points is actually implemented in your code. Note that this is a crucial mandatory step that must not be ommitted.

I'd advocate for adding this explicitly in the cpace.c file, even if this is implicitly guaranteed by some other code section (that might disallow neutral elements as input for scalar multiplications).

FYI: Here is the code of the reference implementation 

https://github.com/BjoernMHaase/AuCPace

One might be adding corresponding code and documentation for the ristretto25519 case, such that the test vectors to be added to the specification could be in line with your implementation.

Yours,

Björn.

**Comment by jedisct1** [comment]
Hi Bjoern,

All the `crypto_scalarmult_*()` functions from libsodium unconditionally check for the identity element (and for low-order points, but that doesn't apply to Ristretto). 

And this implementation properly checks the return value of these functions (they have the `warn_unused_result` attribute, so not doing so would immediately cause the compiler to complain).

An additional check would be redundant.

That check might be missing in the Rust implementation, though.

**Comment by jedisct1** [comment]
A comment has been added to the code to clarify this. Thanks!

**Comment by jedisct1** [comment]
Something a bit surprising in the current draft is the `CI` definition `CI = A || B || AD`.

While it may not be an issue in most applications, having domain separation between `A`, `B` and `AD` may be desirable.

To achieve this, applications can construct `A` and `B` so that they are length-prefixed, which is what this implementation does, but maybe this point would be worth addressing in the document.

**Comment by BjoernMHaase** [comment]
Hi Frank,

 

>While it may not be an issue in most applications, having domain separation between A, B and AD may be desirable.


 


yes this is a good point. I think that this should really be fixed.

 

I think that it would be worthwile to adapt the draft quite soon and agree on a detailed specification for ristretto with test vectors, also regarding the way the mapping step is implemented.

 

Is your code already out in the world in form of an official release? If not, it might be worthwile fixing and modifying the spec. until say, the end of next week.

 

BTW, if you have any feedback regarding the write-up of the I-D, I'd appreciate your commets. I am not experienced with writing this type of specification.

 

Yours,

 

Björn.

 


 

Gesendet: Donnerstag, 14. Mai 2020 um 11:49 Uhr
Von: "Frank Denis" <notifications@github.com>
An: "jedisct1/cpace" <cpace@noreply.github.com>
Cc: "BjoernMHaase" <bjoern.m.haase@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [jedisct1/cpace] Is checking of received remote group elements against the neutral element actually properly implemented? (#1)


 

Something a bit surprising in the current draft is the CI definition CI = A || B || AD.

While it may not be an issue in most applications, having domain separation between A, B and AD may be desirable.

To achieve this, applications can construct A and B so that they are length-prefixed, which is what this implementation does, but maybe this point would be worth addressing in the document.

**Comment by jedisct1** [comment]
Hi Björn,

There hasn't been any formal release of that code, so it can totally be changed as well as the specification.

The I-D is excellent, and contains everything an implementer would need.

Just some minor remarks:

> "Cipher suites for modern Montgomery or Edwards curves are recommended to be specified in line with the definitions for Curve25519". 

Not exactly. Points on Edwards curves usually represented as their Y coordinate. And the Montgomery ladder doesn't work here, so stripping the bit sign may not be required.

Maybe adding a few lines about Edwards curves, possibly with edwards255 being included in the ciphersuite, as well as relevant test vectors, could be useful.

> DSI1 & DS2

DSI1 and DSI2 use `Cpace25519-` for X25519 and `CPace-P256-`.

This is not a consistent naming scheme. Maybe use `Cpace-X25519-` instead of `Cpace25519-`? That would also leave room for `Cpace-Edwards25519-`.

> CI data examples: "One first example of CI data is an encoding of the concatenation of IP addresses and port numbers of both parties"

Source port numbers change for every datagram, and for TCP, the destination port number is often fixed (and, today, mostly only 443). Applications may not even have access to source port numbers. I'm not sure that port numbers are a good example of data to include.

**Comment by BjoernMHaase** [comment]
Link to the general collection of feedback regarding the CPace draft.

https://github.com/BjoernMHaase/AuCPace/issues/3

Link to a recent related post on the CFRG mailing list

https://mailarchive.ietf.org/arch/msg/cfrg/jwV8c0BWwXdhQkPRB7yRz_zFmAg/
